apiVersion:  v1
kind:  Service
metadata:
    name:  vector-service
    namespace: ai-platform
spec:
    selector:
        app:  vector-service
    ports:
        -  port:  80
            targetPort:  8080
