apiVersion:  v1
kind:  Service
metadata:
    name:  inference-service
    namespace:  ai-platform
spec:
    selector:
        app:  inference-service
    ports:
        -  port:  80
            targetPort:  8080
